### ISSUE TITLE
Suggestion/error - Add possibility for excluding worlds

### ISSUE THREAD

**Issue by Hashiri-CZ** [Mitality/BodyHealthLegacy#1]
Hello, 

could you please add possibility to exclude some worlds in the config? 
This is very handy on spawn worlds, where is normally damage turned off, however if players jumps from too high place it will still broke players legs and he cannot move.
We have on spawn auto heal flags in WG, however that did not heal the legs just generated warnings in the log. 

Thank you! :) 

`[10:19:10] [Craft Scheduler Thread - 33 - BodyHealthLegacy/ERROR]: Thread Craft Scheduler Thread - 33 - BodyHealthLegacy failed main thread check: effect add
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:520) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:515) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at mitality.bodyHealthLegacy.effects.BodyHealthEffects.removeEffect(BodyHealthEffects.java:215) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.effects.BodyHealthEffects.removeEffects(BodyHealthEffects.java:72) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.effects.BodyHealthEffects.onBodyPartStateChange(BodyHealthEffects.java:41) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.core.BodyHealth.regenerateHealth(BodyHealth.java:58) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.listeners.BodyHealthListener$1.run(BodyHealthListener.java:198) ~[BodyHealthLegacy-1.0.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:19:10] [Craft Scheduler Thread - 33 - BodyHealthLegacy/WARN]: [BodyHealthLegacy] Plugin BodyHealthLegacy v1.0 generated an exception while executing task 23576
java.lang.IllegalStateException: Asynchronous effect add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:520) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:515) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at mitality.bodyHealthLegacy.effects.BodyHealthEffects.removeEffect(BodyHealthEffects.java:215) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.effects.BodyHealthEffects.removeEffects(BodyHealthEffects.java:72) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.effects.BodyHealthEffects.onBodyPartStateChange(BodyHealthEffects.java:41) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.core.BodyHealth.regenerateHealth(BodyHealth.java:58) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.listeners.BodyHealthListener$1.run(BodyHealthListener.java:198) ~[BodyHealthLegacy-1.0.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:19:10] [Craft Scheduler Thread - 10 - BodyHealthLegacy/WARN]: [BodyHealthLegacy] Plugin BodyHealthLegacy v1.0 generated an exception while executing task 23580
java.lang.IllegalStateException: EntityPotionEffectEvent may only be triggered synchronously.
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactory.java:1904) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactory.java:1894) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactory.java:1879) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.world.entity.LivingEntity.c(LivingEntity.java:1278) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.removeEffect(LivingEntity.java:1291) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.removePotionEffect(CraftLivingEntity.java:547) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at mitality.bodyHealthLegacy.effects.BodyHealthEffects.removeEffect(BodyHealthEffects.java:218) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.effects.BodyHealthEffects.removeEffects(BodyHealthEffects.java:72) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.effects.BodyHealthEffects.onBodyPartStateChange(BodyHealthEffects.java:41) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.core.BodyHealth.regenerateHealth(BodyHealth.java:58) ~[BodyHealthLegacy-1.0.jar:?]
	at mitality.bodyHealthLegacy.listeners.BodyHealthListener$1.run(BodyHealthListener.java:198) ~[BodyHealthLegacy-1.0.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Mitality** [comment]
Hi, yeah, will do that

**Comment by Mitality** [comment]
Please try version 1.4.2 and let me know if my additions there solved your problem :)
EDIT: For the Legacy version it's v2.1 - same changes

**Comment by Mitality** [comment]
Did that resolve your issue(s), or is there still something you want me to add/change for you?

**Comment by Mitality** [comment]
Oh wait, same account as the other issue

**Comment by Mitality** [comment]
I'll close this aswell then :)
